---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python3
      raw: apt-get update && apt-get install -y python3 python3-pip sudo
      register: apt_update
      retries: 3
      delay: 10
      until: apt_update is success
